import { useEffect, useMemo, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { useLocation, useNavigate } from 'react-router-dom';
import { open as openDialog, save } from '@tauri-apps/plugin-dialog';
import { open as openUrl } from '@tauri-apps/plugin-shell';
import { type Update } from '@tauri-apps/plugin-updater';
import { listen } from '@tauri-apps/api/event';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useUpdateStore } from '../store/useUpdateStore';
import {
  LoaderCircle,
} from 'lucide-react';
import { getVersion } from '@tauri-apps/api/app';
import PageTransition from '../components/PageTransition';
import PageSignalField from '../components/PageSignalField';
import Modal from '../components/Modal';
import ResonanceCloseButton from '../components/ResonanceCloseButton';
import ResonanceActionIcon from '../components/ResonanceActionIcon';
import ResonanceIcon from '../components/ResonanceModeIcon';
import { ShareMaskedInput } from '../components/ShareMaskedField';
import ResonanceEmptyState from '../components/ResonanceEmptyState';
import ThemedDateInput from '../components/ThemedDateInput';
import { useUiFeedback } from '../hooks/useUiFeedback';
import { playUiFeedback } from '../lib/uiFeedback';
import { gachaApi } from '../services/tauri-api';
import { useGachaStore } from '../store/useGachaStore';
import { displayPath, displaySensitiveText, displayUid, shareSafeFileToken } from '../lib/shareMode';
import {
  getSyncFreshness,
  daysSince,
  SYNC_WARN_DAYS,
  SYNC_DANGER_DAYS,
  type SyncFreshness,
} from '../lib/utils';
import type { GameDirValidation, PoolBoundaryStatus, RecordSummary, ResourcePackStatus } from '../types';

type DeleteTarget = { playerId: string | null };
type ExportTarget = { playerId: string; earliestDate: string; latestDate: string };
type BoundaryNavigationState = { boundaryPlayerId?: string; boundaryPoolType?: string };

// Directory checks are stable for the lifetime of the app. Keep them across route remounts.
const gameDirValidationCache = new Map<string, GameDirValidation>();

// 去除 release notes 末尾由模板自动生成的下载提示和自动生成标记
// 这些内容在 GitHub Release 页面有意义，但出现在更新弹窗中不合适
function stripUpdateNotesFooter(body: string): string {
  const markers = ['下载文件见下方 Assets', 'Auto-generated by GitHub Actions'];
  const lines = body.split('\n').filter((line) => !markers.some((m) => line.includes(m)));
  // 去除因移除尾部内容而残留的 --- 分隔线和多余空行
  let result = lines.join('\n').replace(/\n+$/, '');
  result = result.replace(/---\s*$/, '').replace(/\n+$/, '');
  return result;
}

export default function SettingsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const settings = useGachaStore((state) => state.settings);
  const fetchSettings = useGachaStore((state) => state.fetchSettings);
  const saveGameDir = useGachaStore((state) => state.saveGameDir);
  const clearRecords = useGachaStore((state) => state.clearRecords);
  const pools = useGachaStore((state) => state.pools);
  const addToast = useGachaStore((state) => state.addToast);
  const storeSummaries = useGachaStore((state) => state.summaries);
  const fetchSummaries = useGachaStore((state) => state.fetchSummaries);
  const [gameDirInput, setGameDirInput] = useState('');
  const [saving, setSaving] = useState(false);
  const [validating, setValidating] = useState(false);
  const [validation, setValidation] = useState<GameDirValidation | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(pools.length > 0 && storeSummaries.length === 0);
  const [summaryError, setSummaryError] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null);
  const [exportTarget, setExportTarget] = useState<ExportTarget | null>(null);
  const [exportMode, setExportMode] = useState<'all' | 'custom'>('all');
  const [exportStartDate, setExportStartDate] = useState('');
  const [exportEndDate, setExportEndDate] = useState('');
  const [exporting, setExporting] = useState(false);
  const [confirmationText, setConfirmationText] = useState('');
  const [deleting, setDeleting] = useState(false);
  const [lastBackupPath, setLastBackupPath] = useState<string | null>(null);
  const [boundaryStatuses, setBoundaryStatuses] = useState<Record<string, PoolBoundaryStatus[]>>({});
  const [boundaryPlayerId, setBoundaryPlayerId] = useState<string | null>(null);
  const [boundaryConfirmation, setBoundaryConfirmation] = useState<PoolBoundaryStatus | null>(null);
  const [highlightedBoundaryPoolType, setHighlightedBoundaryPoolType] = useState<string | null>(null);
  const [fadingBoundaryHighlight, setFadingBoundaryHighlight] = useState(false);
  const boundaryHighlightTimerRef = useRef<number | null>(null);
  const boundaryHighlightFadeTimerRef = useRef<number | null>(null);
  const [boundarySaving, setBoundarySaving] = useState(false);
  const [completionPulls, setCompletionPulls] = useState('');
  const [updateInfo, setUpdateInfo] = useState<Update | null>(null);
  const availableUpdate = useUpdateStore((state) => state.availableUpdate);
  const checkingUpdate = useUpdateStore((state) => state.checking);
  const manualCheck = useUpdateStore((state) => state.manualCheck);
  const [updating, setUpdating] = useState(false);
  const [updateProgress, setUpdateProgress] = useState(0);
  const [appVersion, setAppVersion] = useState('');
  const [resourcePack, setResourcePack] = useState<ResourcePackStatus | null>(null);
  const [resourcePackBusy, setResourcePackBusy] = useState(false);
  const { enabled: soundEnabled, setEnabled: setSoundEnabled } = useUiFeedback();

  useEffect(() => {
    let cancelled = false;
    let timer: number | null = null;
    const refreshStatus = async () => {
      try {
        const status = await gachaApi.getResourcePackStatus();
        if (!cancelled) setResourcePack(status);
      } catch {
        // Browser preview and app shutdown can make the command unavailable.
      } finally {
        if (!cancelled) timer = window.setTimeout(refreshStatus, 500);
      }
    };
    void refreshStatus();
    return () => {
      cancelled = true;
      if (timer !== null) window.clearTimeout(timer);
    };
  }, []);

  useEffect(() => {
    if (!settings) fetchSettings();
  }, [fetchSettings, settings]);

  useEffect(() => {
    getVersion().then(setAppVersion).catch(() => {});
  }, []);

  useEffect(() => {
    if (settings) setGameDirInput(settings.game_dir);
  }, [settings]);

  useEffect(() => {
    if (pools.length === 0) {
      setBoundaryStatuses({});
      return;
    }
    let cancelled = false;
    Promise.all(pools.map(async (playerId) => [playerId, await gachaApi.getPoolBoundaryStatuses(playerId)] as const))
      .then((entries) => { if (!cancelled) setBoundaryStatuses(Object.fromEntries(entries)); })
      .catch(() => { if (!cancelled) setBoundaryStatuses({}); });
    return () => { cancelled = true; };
  }, [pools, storeSummaries]);

  useEffect(() => {
    const requested = (location.state ?? {}) as BoundaryNavigationState;
    const playerId = requested.boundaryPlayerId;
    const poolType = requested.boundaryPoolType;
    if (!playerId || !boundaryStatuses[playerId]) return;

    setBoundaryPlayerId(playerId);
    setHighlightedBoundaryPoolType(poolType ?? null);
    setFadingBoundaryHighlight(false);
    if (boundaryHighlightTimerRef.current !== null) {
      window.clearTimeout(boundaryHighlightTimerRef.current);
    }
    if (boundaryHighlightFadeTimerRef.current !== null) {
      window.clearTimeout(boundaryHighlightFadeTimerRef.current);
    }
    boundaryHighlightTimerRef.current = window.setTimeout(() => {
      setFadingBoundaryHighlight(true);
      boundaryHighlightTimerRef.current = null;
      boundaryHighlightFadeTimerRef.current = window.setTimeout(() => {
        setHighlightedBoundaryPoolType(null);
        setFadingBoundaryHighlight(false);
        boundaryHighlightFadeTimerRef.current = null;
      }, 700);
    }, 2500);
    navigate(location.pathname, { replace: true, state: null });
  }, [boundaryStatuses, location.pathname, location.state, navigate]);

  useEffect(() => () => {
    if (boundaryHighlightTimerRef.current !== null) {
      window.clearTimeout(boundaryHighlightTimerRef.current);
    }
    if (boundaryHighlightFadeTimerRef.current !== null) {
      window.clearTimeout(boundaryHighlightFadeTimerRef.current);
    }
  }, []);

  const refreshBoundaryStatuses = async (playerId: string) => {
    const statuses = await gachaApi.getPoolBoundaryStatuses(playerId);
    setBoundaryStatuses((current) => ({ ...current, [playerId]: statuses }));
  };

  const handleBoundaryConfirmation = async () => {
    if (!boundaryPlayerId || !boundaryConfirmation) return;
    if (!boundaryConfirmation.confirmed && completionPulls.trim() !== '') {
      await handleBoundaryCompletion();
      return;
    }
    setBoundarySaving(true);
    const confirmed = !boundaryConfirmation.confirmed;
    try {
      await gachaApi.setPoolBoundaryConfirmed(boundaryPlayerId, boundaryConfirmation.pool_type, confirmed);
      await Promise.all([
        refreshBoundaryStatuses(boundaryPlayerId),
        fetchSummaries(),
        useGachaStore.getState().fetchRecords(),
        useGachaStore.getState().fetchStats(boundaryPlayerId),
      ]);
      addToast('success', confirmed ? '已将该卡池现存记录确认为完整起点' : '已恢复首段历史边界提示');
      setBoundaryConfirmation(null);
    } catch (error) {
      addToast('error', String(error));
    } finally {
      setBoundarySaving(false);
    }
  };

  useEffect(() => {
    const path = gameDirInput.trim();
    if (!path) {
      setValidation(null);
      setValidating(false);
      return;
    }

    const cached = gameDirValidationCache.get(path);
    if (cached) {
      setValidation(cached);
      setValidating(false);
      if (cached.valid && cached.normalized_game_dir !== path) {
        setGameDirInput(cached.normalized_game_dir);
      }
      return;
    }

    let cancelled = false;
    setValidating(true);
    const timer = window.setTimeout(async () => {
      try {
        const result = await gachaApi.validateGameDir(path);
        gameDirValidationCache.set(path, result);
        if (!cancelled) {
          gameDirValidationCache.set(result.normalized_game_dir, result);
          setValidation(result);
          if (result.valid && result.normalized_game_dir !== path) {
            setGameDirInput(result.normalized_game_dir);
          }
        }
      } catch {
        if (!cancelled) {
          const result = { valid: false, log_path: '', normalized_game_dir: path, message: '目录校验失败，请重新选择' };
          gameDirValidationCache.set(path, result);
          setValidation(result);
        }
      } finally {
        if (!cancelled) setValidating(false);
      }
    }, 300);

    return () => {
      cancelled = true;
      window.clearTimeout(timer);
    };
  }, [gameDirInput]);

  // 订阅 store.summaries；进入设置页时确保拉取过一次（有 pools 但 summaries 空时触发）
  useEffect(() => {
    if (pools.length === 0) {
      setSummaryLoading(false);
      setSummaryError(false);
      return;
    }
    if (storeSummaries.length > 0) {
      setSummaryLoading(false);
      setSummaryError(false);
      return;
    }
    let cancelled = false;
    setSummaryLoading(true);
    setSummaryError(false);
    fetchSummaries()
      .then(() => {
        if (!cancelled) setSummaryLoading(false);
      })
      .catch(() => {
        if (!cancelled) {
          setSummaryError(true);
          setSummaryLoading(false);
        }
      });
    return () => { cancelled = true; };
  }, [pools, storeSummaries.length, fetchSummaries]);

  // 直接用 store 的 summaries，保证删除/清空/新增玩家后立即同步
  const summaries = storeSummaries;

  const summaryByPlayer = useMemo(
    () => new Map(summaries.map((summary) => [summary.player_id, summary])),
    [summaries],
  );
  const totalRecords = summaries.reduce((sum, summary) => sum + summary.record_count, 0);
  const savedPath = settings?.game_dir.trim() ?? '';
  const isDirty = gameDirInput.trim() !== savedPath;
  const directoryState = !gameDirInput.trim()
    ? { label: '未配置', tone: 'idle' }
    : validating
      ? { label: '校验中', tone: 'checking' }
      : validation?.valid
        ? { label: '目录可用', tone: 'ready' }
        : { label: '需要检查', tone: 'error' };

  const selectedSummary = deleteTarget?.playerId ? summaryByPlayer.get(deleteTarget.playerId) : null;
  const expectedConfirmation = deleteTarget?.playerId ? displayUid(deleteTarget.playerId) : '清空全部数据';
  const targetRecordCount = deleteTarget?.playerId ? selectedSummary?.record_count ?? 0 : totalRecords;

  // 展示用的辅助函数：每个玩家 → 记录范围（完整日期段） + 最近同步时间（单点）
  const formatSummaryMeta = (summary: RecordSummary | undefined) => {
    if (!summary) return { recordRange: '', lastImportedAt: '', hasImport: false, impInferred: false };
    const recordRange = `${summary.earliest_time.slice(0, 10)} 至 ${summary.latest_time.slice(0, 10)}`;
    const hasImport = Boolean(summary.last_imported_at);
    const lastImportedAt = hasImport ? summary.last_imported_at!.slice(0, 10) : '';
    return {
      recordRange,
      lastImportedAt,
      hasImport,
      impInferred: summary.is_inferred === true,
    };
  };

  // 清空全部时聚合所有玩家的记录范围和最近同步时间
  const overallMeta = useMemo(() => {
    if (summaries.length === 0) return { recordRange: '', lastImportedAt: '', hasImport: false, impInferred: false };
    const earliestRecord = summaries.reduce((min, item) => (item.earliest_time < min ? item.earliest_time : min), summaries[0].earliest_time);
    const latestRecord = summaries.reduce((max, item) => (item.latest_time > max ? item.latest_time : max), summaries[0].latest_time);
    const lastImported = summaries
      .filter((item) => item.last_imported_at)
      .map((item) => item.last_imported_at!)
      .reduce((max, t) => (t > max ? t : max), '');
    return {
      recordRange: `${earliestRecord.slice(0, 10)} 至 ${latestRecord.slice(0, 10)}`,
      lastImportedAt: lastImported ? lastImported.slice(0, 10) : '',
      hasImport: Boolean(lastImported),
      impInferred: summaries.every((item) => item.is_inferred === true),
    };
  }, [summaries]);

  const targetMeta = selectedSummary ? formatSummaryMeta(selectedSummary) : overallMeta;

  // 玩家 freshness 分级（warn: 120~180 天久未同步 / danger: >180 天可能缺数据）
  const freshnessInfo = useMemo(() => {
    const map = new Map<string, { freshness: SyncFreshness; daysAgo: number }>();
    summaries.forEach((summary) => {
      const freshness = getSyncFreshness(summary.last_imported_at, summary.is_inferred);
      const daysAgo = summary.last_imported_at ? daysSince(summary.last_imported_at) : 0;
      map.set(summary.player_id, { freshness, daysAgo });
    });
    return map;
  }, [summaries]);

  // 是否有任何一个玩家处于 warn 或 danger（用来切换顶部提示条的颜色）
  const anyWarn = useMemo(
    () => summaries.some((summary) => getSyncFreshness(summary.last_imported_at, summary.is_inferred) === 'warn'),
    [summaries],
  );
  const anyDanger = useMemo(
    () => summaries.some((summary) => getSyncFreshness(summary.last_imported_at, summary.is_inferred) === 'danger'),
    [summaries],
  );
  const anyStale = anyWarn || anyDanger;

  const staleCardTip = (freshness: SyncFreshness, daysAgo: number) => {
    if (freshness === 'danger') {
      return `距上次同步已 ${daysAgo} 天（超过 ${SYNC_DANGER_DAYS} 天阈值）。官方链接通常只保留近 6 个月，这段时间可能已存在数据遗漏（若期间未抽卡则不会丢数据）。`;
    }
    return `距上次同步已 ${daysAgo} 天（超过 ${SYNC_WARN_DAYS} 天阈值）。建议尽快同步以免丢失 6 个月临界区的缺口。`;
  };

  const handleSelectFolder = async () => {
    try {
      const selected = await openDialog({ directory: true, multiple: false, title: '选择鸣潮游戏目录' });
      if (selected) setGameDirInput(selected);
    } catch {
      addToast('error', '无法打开目录选择器');
    }
  };

  const handleSave = async () => {
    if (!isDirty || !validation?.valid) return;
    setSaving(true);
    try {
      await saveGameDir(gameDirInput.trim());
    } catch {
      // Store 已显示失败提示。
    } finally {
      setSaving(false);
    }
  };

  const openDeleteDialog = (playerId: string | null) => {
    setConfirmationText('');
    setDeleteTarget({ playerId });
  };

  const closeDeleteDialog = () => {
    if (deleting) return;
    setDeleteTarget(null);
    setConfirmationText('');
  };

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    const result = await clearRecords(deleteTarget.playerId ?? undefined);
    setDeleting(false);
    if (!result) return;
    setLastBackupPath(result.backup_path);
    setDeleteTarget(null);
    setConfirmationText('');
  };

  const copyBackupPath = async () => {
    if (!lastBackupPath) return;
    try {
      await navigator.clipboard.writeText(displayPath(lastBackupPath));
      addToast('success', '备份路径已复制');
    } catch {
      addToast('error', '复制失败');
    }
  };

  const openBackupDirectory = async () => {
    try {
      await gachaApi.openBackupDirectory();
    } catch (error) {
      addToast('error', `无法打开备份目录: ${String(error)}`);
    }
  };

  const openExportDialog = (playerId: string, summary?: RecordSummary) => {
    const earliestDate = summary?.earliest_time.slice(0, 10) ?? '';
    const latestDate = summary?.latest_time.slice(0, 10) ?? '';
    setExportTarget({ playerId, earliestDate, latestDate });
    setExportMode('all');
    setExportStartDate(earliestDate);
    setExportEndDate(latestDate);
  };

  const closeExportDialog = () => {
    if (exporting) return;
    setExportTarget(null);
  };

  const handleExport = async () => {
    if (!exportTarget) return;
    const customRange = exportMode === 'custom';
    if (customRange && (!exportStartDate || !exportEndDate || exportStartDate > exportEndDate)) return;
    try {
      setExporting(true);
      const suffix = customRange ? `${exportStartDate}_${exportEndDate}` : 'all';
      const path = await save({
        defaultPath: `uid_${shareSafeFileToken(exportTarget.playerId)}_${suffix}.json`,
        filters: [{ name: 'JSON', extensions: ['json'] }],
      });
      if (!path) return;
      await gachaApi.exportGachaJson(
        exportTarget.playerId,
        path,
        customRange ? exportStartDate : undefined,
        customRange ? exportEndDate : undefined,
      );
      setExportTarget(null);
      addToast('success', customRange ? '指定时间范围记录已导出' : '全部记录已导出');
    } catch (e) {
      addToast('error', `导出失败: ${String(e)}`);
    } finally {
      setExporting(false);
    }
  };

  const handleCheckUpdate = async () => {
    try {
      const update = await manualCheck();
      if (update) {
        setUpdateInfo(update);
      } else {
        addToast('success', '已是最新版本');
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      addToast('error', `检查更新失败: ${msg}`);
    }
  };

  const handleInstallUpdate = async () => {
    if (!updateInfo) return;
    setUpdating(true);
    setUpdateProgress(0);

    const unlistenFns: Array<() => void> = [];
    const lastProxyRef = { current: '' };
    try {
      const platforms = (updateInfo.rawJson.platforms ?? {}) as Record<string, { url?: string; signature?: string }>;
      const ua = navigator.userAgent.toLowerCase();
      const platformKey = ua.includes('win')
        ? 'windows-x86_64'
        : ua.includes('mac')
          ? (navigator.userAgent.includes('aarch64') || navigator.userAgent.includes('arm64') ? 'darwin-aarch64' : 'darwin-x86_64')
          : 'linux-x86_64';
      const info = platforms[platformKey];
      const officialUrl = info?.url;
      if (!officialUrl) throw new Error('latest.json 未包含安装包下载地址');

      // 注册进度事件（仅代理切换时提示一次）
      const unlistenProgress = await listen<{ proxy: string; percent: number }>(
        'update-download-progress',
        (event) => {
          const { proxy, percent } = event.payload;
          if (proxy !== lastProxyRef.current) {
            lastProxyRef.current = proxy;
            addToast('info', `通过 ${proxy} 下载中...`);
          }
          setUpdateProgress(percent);
        },
      );
      unlistenFns.push(unlistenProgress);

      const unlistenDone = await listen<{ path: string }>(
        'update-download-done',
        () => {
          addToast('success', '下载完成，正在安装...');
        },
      );
      unlistenFns.push(unlistenDone);

      await gachaApi.downloadAndInstallUpdate(officialUrl, updateInfo.version);
      setUpdateProgress(100);

      // 给前端一点时间渲染完成态，然后由 NSIS 静默安装并退出当前应用
      await new Promise((resolve) => window.setTimeout(resolve, 800));
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      addToast('error', `更新失败: ${msg}`);
      setUpdating(false);
    } finally {
      unlistenFns.forEach((fn) => fn());
    }
  };

  const closeUpdateModal = () => {
    if (updating) return;
    setUpdateInfo(null);
    setUpdateProgress(0);
  };

  const handleOpenLogDirectory = async () => {
    try {
      await gachaApi.openLogDirectory();
    } catch (error) {
      addToast('error', `打开日志目录失败: ${String(error)}`);
    }
  };

  const handleBoundaryCompletion = async () => {
    if (!boundaryPlayerId || !boundaryConfirmation) return;
    const target = Number(completionPulls);
    if (!Number.isInteger(target) || target < 1 || target > (boundaryConfirmation.pool_type === '5' ? 50 : 80)) {
      addToast('error', '请输入有效的目标抽数');
      return;
    }
    setBoundarySaving(true);
    try {
      const inserted = await gachaApi.completePoolBoundary(boundaryPlayerId, boundaryConfirmation.pool_type, target);
      await Promise.all([
        refreshBoundaryStatuses(boundaryPlayerId),
        fetchSummaries(),
        useGachaStore.getState().fetchRecords(),
        useGachaStore.getState().fetchStats(boundaryPlayerId),
      ]);
      addToast('success', `已补足 ${inserted.length} 条模拟三星/四星记录，目标区间为 ${target} 抽`);
      setBoundaryConfirmation(null);
    } catch (error) {
      addToast('error', String(error));
    } finally {
      setBoundarySaving(false);
    }
  };

  const handleRefreshResourcePack = async () => {
    if (resourcePackBusy || resourcePack?.in_progress) return;
    setResourcePackBusy(true);
    try {
      const status = await gachaApi.refreshResourcePack();
      setResourcePack(status);
      addToast('success', status.installed ? '资源包已更新并可用' : '资源包检查完成');
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      try {
        setResourcePack(await gachaApi.getResourcePackStatus());
      } catch {
        setResourcePack((current) => current ? { ...current, last_error: message } : current);
      }
      addToast('error', `资源包下载失败：${message}`);
    } finally {
      setResourcePackBusy(false);
    }
  };

  const resourcePackDownloading = resourcePackBusy || resourcePack?.in_progress === true;
  const resourcePackPercent = resourcePack?.total
    ? Math.min(100, Math.floor(resourcePack.downloaded / resourcePack.total * 100))
    : null;
  const resourcePackAction = resourcePack?.last_error
    ? '重试下载'
    : resourcePack?.installed
      ? '检查更新'
      : '下载资源包';

  return (
    <PageTransition>
      <div className="page-scroll h-full overflow-y-auto overflow-x-hidden">
        <div className="page-container settings-page-container w-full space-y-5 p-6">
          <header className="page-header settings-page-header py-1">
            <PageSignalField variant="settings" />
            <h1 className="page-title text-xl font-semibold text-tide">设置</h1>
            <p className="page-subtitle mt-1 text-xs text-wave">管理扫描目录与本地数据</p>
          </header>

          <div className="settings-console-grid grid items-start gap-4 md:grid-cols-[minmax(0,0.9fr)_minmax(360px,1.1fr)]">
            <div className="space-y-4">
              <motion.section
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                className="resonance-panel settings-panel settings-control-panel settings-directory-panel p-5"
              >
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2 text-sm font-medium text-tide">
                    <ResonanceActionIcon tone="gold"><ResonanceIcon kind="directory" size={15} /></ResonanceActionIcon>游戏目录
                  </div>
                  <div className="settings-state-readout" data-state={directoryState.tone}>
                    <span className="settings-state-pulse" />
                    <span>{directoryState.label}</span>
                  </div>
                </div>
                <p className="mt-1 text-xs text-wave">请选择包含 <span className="text-tide">Client</span> 文件夹的游戏根目录，软件会自动查找 <span className="font-mono text-[11px]">Client\Saved\Logs\Client.log</span></p>

                <label className="mt-5 block">
                  <span className="mb-2 block text-xs text-wave">游戏根目录</span>
                  <div className="flex gap-2">
                    <ShareMaskedInput
                      type="text"
                      value={gameDirInput}
                      displayValue={displayPath(gameDirInput)}
                      onChange={(event) => setGameDirInput(event.target.value)}
                      placeholder="例如: E:\Wuthering Waves\Wuthering Waves Game"
                      containerClassName="min-w-0 flex-1"
                      className="glass-input w-full px-3 py-2.5 text-sm"
                    />
                    <button onClick={handleSelectFolder} className="glass-input flex shrink-0 items-center gap-2 px-3 py-2.5 text-sm text-wave hover:text-tide">
                      <ResonanceActionIcon size="sm"><ResonanceIcon kind="directory" size={14} /></ResonanceActionIcon>选择
                    </button>
                  </div>
                </label>

                <div className="mt-2 min-h-5">
                  {!gameDirInput.trim() ? (
                    <div className="flex items-center gap-2 text-[11px] text-wave"><ResonanceIcon kind="info" size={13} />尚未设置游戏目录</div>
                  ) : validating ? (
                    <div className="flex items-center gap-2 text-[11px] text-wave"><LoaderCircle size={12} className="animate-spin" />正在检查 Client.log</div>
                  ) : validation?.valid ? (
                    <div className="flex items-center gap-2 text-[11px] text-[#8fc8be]"><ResonanceIcon kind="success" size={13} />{displaySensitiveText(validation.message)}</div>
                  ) : (
                    <div className="flex items-center gap-2 text-[11px] text-[#d99a9a]"><ResonanceIcon kind="error" size={13} />{displaySensitiveText(validation?.message)}</div>
                  )}
                </div>

                <div className="mt-4 flex items-center gap-3">
                  <button
                    onClick={handleSave}
                    disabled={saving || validating || !isDirty || !validation?.valid}
                    className="tide-btn flex items-center gap-2 px-4 py-2 text-sm disabled:opacity-40"
                  >
                    <ResonanceActionIcon size="sm" tone="gold">
                      {saving ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind="save" size={14} />}
                    </ResonanceActionIcon>
                    {saving ? '保存中' : '保存目录'}
                  </button>
                  {isDirty && validation?.valid && <span className="text-[11px] text-[#c9ab78]">有未保存的修改</span>}
                  {!isDirty && savedPath && <span className="text-[11px] text-wave">当前设置已保存</span>}
                </div>
              </motion.section>

              <motion.section
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.03 }}
                className="resonance-panel settings-panel settings-control-panel p-5"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex min-w-0 items-center gap-2 text-sm font-medium text-tide">
                    <ResonanceActionIcon tone="gold"><ResonanceIcon kind="traces" size={15} /></ResonanceActionIcon>
                    本地资源包
                  </div>
                  <button
                    type="button"
                    onClick={() => void handleRefreshResourcePack()}
                    disabled={resourcePackDownloading}
                    className="flex shrink-0 items-center gap-1.5 text-xs text-wave transition-colors hover:text-tide disabled:opacity-50"
                  >
                    <ResonanceActionIcon size="sm">{resourcePackDownloading ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind={resourcePack?.installed ? 'refresh' : 'download'} size={14} />}</ResonanceActionIcon>
                    {resourcePackDownloading ? '下载中' : resourcePackAction}
                  </button>
                </div>
                <div className="mt-3 flex items-center gap-2 text-[11px]">
                  {resourcePackDownloading ? (
                    <><LoaderCircle size={13} className="animate-spin text-wave" /><span className="text-wave">{resourcePack?.phase === 'archive' ? '正在下载资源包' : '正在获取资源包清单'}{resourcePack?.proxy ? ` · ${resourcePack.proxy}` : ''}</span></>
                  ) : resourcePack?.last_error ? (
                    <><ResonanceIcon kind="error" size={13} className="text-[#d99a9a]" /><span className="text-[#d99a9a]">{resourcePack.installed ? '资源包更新失败，本地版本仍可用' : '资源包下载失败，可手动重试'}</span></>
                  ) : resourcePack?.installed ? (
                    <><ResonanceIcon kind="success" size={13} className="text-[#8fc8be]" /><span className="text-[#8fc8be]">已安装 · v{resourcePack.version}</span></>
                  ) : (
                    <><ResonanceIcon kind="info" size={13} className="text-wave" /><span className="text-wave">尚未安装，应用启动后会自动下载</span></>
                  )}
                </div>
                {resourcePackDownloading && (
                  <div className="mt-2">
                    <div className="flex justify-between text-[10px] text-wave">
                      <span>{resourcePack?.phase === 'archive' ? '资源包' : '清单'}</span>
                      <span>{resourcePackPercent === null ? '准备中' : `${resourcePackPercent}%`}</span>
                    </div>
                    <div className="mt-1 h-1.5 overflow-hidden bg-white/[0.08]"><div className="h-full bg-[#8fc8be] transition-[width] duration-200" style={{ width: resourcePackPercent === null ? '8%' : `${resourcePackPercent}%` }} /></div>
                  </div>
                )}
                {resourcePack?.installed && !resourcePack.last_error && (
                  <p className="mt-2 text-[11px] leading-5 text-wave">包含 {resourcePack.resource_count.toLocaleString()} 项素材、{resourcePack.icon_count.toLocaleString()} 张图标和 {resourcePack.portrait_count.toLocaleString()} 张立绘。</p>
                )}
                {resourcePack?.last_error && <p className="mt-2 break-words text-[11px] leading-5 text-[#d99a9a]">{displaySensitiveText(resourcePack.last_error)}</p>}
              </motion.section>

              <section className="feedback-preference-row">
                <div className="flex min-w-0 items-center gap-3">
                  <span className="feedback-preference-icon"><ResonanceIcon kind="activity" size={16} /></span>
                  <div className="min-w-0">
                    <div className="text-xs font-medium text-tide">频率反馈</div>
                    <div className="mt-0.5 text-[11px] text-wave">扫描、导入和插入记录完成时播放轻提示音</div>
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <button type="button" onClick={() => void playUiFeedback('record-inserted')} disabled={!soundEnabled} className="feedback-preview-button">试听</button>
                  <button
                    type="button"
                    role="switch"
                    aria-checked={soundEnabled}
                    aria-label="频率反馈"
                    onClick={() => {
                      const next = !soundEnabled;
                      setSoundEnabled(next);
                      if (next) void playUiFeedback('scan-complete');
                    }}
                    className="resonance-toggle"
                    data-active={soundEnabled ? 'true' : 'false'}
                  >
                    <span className="resonance-toggle-track" />
                    <span className="resonance-toggle-node" />
                  </button>
                </div>
              </section>

              <section className="border-t border-white/[0.06] px-1 pt-4 text-xs text-wave">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-tide-dim">Wuwa Gacha Tool v{appVersion}</span>
                    {availableUpdate && !updateInfo && (
                      <span className="rounded-sm bg-[#6faaa0]/10 px-1.5 py-0.5 text-[10px] text-[#8fc8be]">
                        有新版本 v{availableUpdate.version}
                      </span>
                    )}
                  </div>
                  <button
                    onClick={handleCheckUpdate}
                    disabled={checkingUpdate}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide disabled:opacity-50"
                  >
                    <ResonanceActionIcon size="sm">
                      {checkingUpdate ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind="refresh" size={15} />}
                    </ResonanceActionIcon>
                    {checkingUpdate ? '检查中' : '检查更新'}
                  </button>
                </div>
                <p className="mt-2 leading-5">数据仅保存在本机，不会上传到服务器。</p>
                <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2">
                  <button
                    onClick={handleOpenLogDirectory}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide"
                  >
                    <ResonanceActionIcon size="sm"><ResonanceIcon kind="log" size={14} /></ResonanceActionIcon>打开日志目录
                  </button>
                  <button
                    onClick={() => void openUrl('https://github.com/juliy819/wuwa-gacha-tool')}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide"
                  >
                    <ResonanceActionIcon size="sm"><ResonanceIcon kind="repository" size={14} /></ResonanceActionIcon>GitHub 仓库
                  </button>
                </div>
              </section>
            </div>

            <motion.section
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.05 }}
              className="resonance-panel settings-panel settings-control-panel settings-data-panel p-5"
            >
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 text-sm font-medium text-tide"><ResonanceActionIcon tone="gold"><ResonanceIcon kind="database" size={15} /></ResonanceActionIcon>本地数据</div>
                  <p className="mt-1 text-xs text-wave">{pools.length} 位玩家 · {totalRecords.toLocaleString()} 条记录</p>
                </div>
                <div className="settings-data-readout" aria-label={`本地共 ${totalRecords.toLocaleString()} 条记录`}>
                  <span className="settings-data-readout-value">{totalRecords.toLocaleString()}</span>
                  <span className="settings-data-readout-label">条记录</span>
                  <span className="settings-data-readout-orbit" aria-hidden="true" />
                </div>
              </div>

              <div
                className={`mt-4 flex items-start gap-2 rounded-md border px-3 py-2.5 text-[11px] leading-5 ${
                  anyDanger
                    ? 'border-[#d84848]/25 bg-[#d84848]/[0.07] text-[#d99a9a]'
                    : anyWarn
                      ? 'border-[#c99a68]/15 bg-[#c99a68]/[0.05] text-[#d9bd9a]'
                      : 'border-[#c9ab78]/15 bg-[#c9ab78]/[0.05] text-[#c9ab78]'
                }`}
              >
                {anyDanger ? (
                  <ResonanceIcon kind="error" size={14} className="mt-0.5 shrink-0 text-[#d84848]" />
                ) : anyWarn ? (
                  <ResonanceIcon kind="warning" size={14} className="mt-0.5 shrink-0 text-[#d09960]" />
                ) : (
                  <ResonanceIcon kind="warning" size={14} className="mt-0.5 shrink-0" />
                )}
                <span>
                  官方抽卡链接仅保留近约 6 个月。建议至少每半年同步一次，超期缺口无法自动补回。
                  {anyDanger && (
                    <span className="ml-2 text-[#d84848]">（检测到超过 {SYNC_DANGER_DAYS} 天未同步，可能已存在数据遗漏）</span>
                  )}
                  {!anyDanger && anyWarn && (
                    <span className="ml-2 text-[#d09960]">（检测到超过 {SYNC_WARN_DAYS} 天未同步，建议尽快同步）</span>
                  )}
                </span>
              </div>

              {lastBackupPath && (
                <div className="mt-3 flex items-center gap-3 rounded-md border border-[#6faaa0]/15 bg-[#6faaa0]/[0.05] px-3 py-2.5">
                  <ResonanceIcon kind="success" size={15} className="shrink-0 text-[#8fc8be]" />
                  <div className="min-w-0 flex-1">
                    <div className="text-[11px] text-[#8fc8be]">删除前备份已创建</div>
                    <div className="mt-0.5 truncate text-[10px] text-wave" title={displayPath(lastBackupPath)}>{displayPath(lastBackupPath)}</div>
                  </div>
                  <button onClick={() => void openBackupDirectory()} className="flex h-7 shrink-0 items-center gap-1 rounded-md px-2 text-[10px] text-wave hover:bg-white/[0.05] hover:text-tide" title="打开备份目录"><ResonanceIcon kind="directory" size={12} />目录</button>
                  <button onClick={copyBackupPath} className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-wave hover:bg-white/[0.05] hover:text-tide" title="复制备份路径"><ResonanceActionIcon size="sm"><ResonanceIcon kind="copy" size={12} /></ResonanceActionIcon></button>
                </div>
              )}

              <div className="mt-4 overflow-hidden rounded-md border border-white/[0.06]">
                {summaryLoading ? (
                  <div className="flex items-center justify-center gap-2 py-10 text-xs text-wave"><LoaderCircle size={14} className="animate-spin" />正在读取数据摘要</div>
                ) : summaryError ? (
                  <div className="py-10 text-center text-xs text-[#d99a9a]">数据摘要读取失败</div>
                ) : pools.length === 0 ? (
                  <ResonanceEmptyState variant="database" compact title="尚未保存抽卡记录" description="完成一次扫描或导入后，本地数据摘要会显示在这里" />
                ) : (
                  <div className="divide-y divide-white/[0.05]">
                    {pools.map((playerId) => {
                      const summary = summaryByPlayer.get(playerId);
                      const boundaries = boundaryStatuses[playerId];
                      const f = freshnessInfo.get(playerId);
                      const freshness = f?.freshness ?? 'fresh';
                      const isWarn = freshness === 'warn';
                      const isDanger = freshness === 'danger';
                      const isStale = isWarn || isDanger;
                      const tip = isStale ? staleCardTip(freshness, f!.daysAgo) : undefined;

                      // 根据 freshness 选配色
                      const palette =
                        isDanger
                          ? {
                              border: 'border-[#d84848]/20',
                              bg: 'bg-[#d84848]/[0.04]',
                              badge: 'border-[#d84848]/25 bg-[#d84848]/[0.08] text-[#d84848]',
                              label: '可能缺数据',
                              icon: 'text-[#d99a9a]',
                            }
                          : isWarn
                            ? {
                                border: 'border-[#c99a68]/20',
                                bg: 'bg-[#c99a68]/[0.04]',
                                badge: 'border-[#c99a68]/25 bg-[#c99a68]/[0.08] text-[#d09960]',
                                label: '久未同步',
                                icon: 'text-[#d9bd9a]',
                              }
                            : null;
                      return (
                        <div
                          key={playerId}
                          className={`relative flex items-center justify-between gap-3 px-3 py-3 ${palette ? palette.bg : ''}`}
                          title={tip}
                        >
                          {palette && (
                            <div className={`pointer-events-none absolute inset-0 rounded-md border ${palette.border}`} />
                          )}
                          <div className="relative min-w-0">
                            <div className="flex items-center gap-1.5">
                              <div className="text-sm text-tide">UID {displayUid(playerId)}</div>
                              {palette && (
                                <span
                                  className={`inline-flex items-center gap-1 rounded border px-1.5 py-px text-[10px] ${palette.badge}`}
                                  title={tip}
                                >
                                  <ResonanceIcon kind={isDanger ? 'error' : 'warning'} size={10} /> {palette.label}
                                </span>
                              )}
                            </div>
                            {summary && (
                              <div className="mt-1 flex flex-col gap-0.5 text-[11px] text-wave">
                                <div className="flex items-center gap-1.5">
                                  <ResonanceIcon kind="database" size={12} className="text-[#8fc8be]" />
                                  <span>记录 {summary.record_count.toLocaleString()} 条 · {summary.earliest_time.slice(0, 10)} 至 {summary.latest_time.slice(0, 10)}</span>
                                </div>
                                {summary.last_imported_at && (
                                  <div className="flex items-center gap-1.5">
                                    <ResonanceIcon
                                      kind="sync"
                                      size={12}
                                      className={palette ? palette.icon : 'text-[#c9ab78]'}
                                    />
                                    <span className={palette ? palette.icon : ''}>
                                      最近同步 {summary.last_imported_at.slice(0, 10)}
                                      {summary.is_inferred && (
                                        <span className="ml-1.5 inline-flex items-center gap-1 rounded border border-[#c9ab78]/25 bg-[#c9ab78]/[0.08] px-1.5 py-px text-[10px] text-[#c9ab78]" title="升级前已导入数据，同步时间由记录范围推断">
                                          <ResonanceIcon kind="info" size={10} /> 推断
                                        </span>
                                      )}
                                    </span>
                                  </div>
                                )}
                              </div>
                            )}
                          </div>
                          <div className="relative flex shrink-0 items-center gap-1">
                            <button
                              onClick={() => setBoundaryPlayerId(playerId)}
                              disabled={!boundaries}
                              className="flex h-8 items-center gap-1.5 rounded-md px-2 text-[10px] text-wave transition-colors hover:bg-white/[0.05] hover:text-tide disabled:cursor-default disabled:opacity-40"
                              title="管理卡池历史起点"
                            >
                              {!boundaries ? <LoaderCircle size={11} className="animate-spin" /> : <ResonanceIcon kind="traces" size={12} />}
                              历史起点
                            </button>
                            <button onClick={() => openExportDialog(playerId, summary)} className="flex h-8 w-8 items-center justify-center rounded-md text-wave hover:bg-white/[0.05] hover:text-tide" title={`导出 UID ${displayUid(playerId)} 的数据`}><ResonanceActionIcon size="sm"><ResonanceIcon kind="download" size={14} /></ResonanceActionIcon></button>
                            <button onClick={() => openDeleteDialog(playerId)} className="flex h-8 w-8 items-center justify-center rounded-md text-wave hover:bg-[#d84848]/10 hover:text-[#d99a9a]" title={`删除 UID ${displayUid(playerId)} 的记录`}><ResonanceActionIcon size="sm" tone="danger"><ResonanceIcon kind="delete" size={14} /></ResonanceActionIcon></button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              <div className="mt-4 flex items-center justify-between border-t border-white/[0.05] pt-4">
                <span className="text-[11px] text-wave">删除前会自动备份数据库</span>
                <button
                  onClick={() => openDeleteDialog(null)}
                  disabled={pools.length === 0}
                  className="flex items-center gap-2 rounded-md border border-[#d84848]/25 px-3 py-2 text-xs text-[#d99a9a] hover:bg-[#d84848]/10 disabled:cursor-not-allowed disabled:opacity-30"
                >
                  <ResonanceActionIcon size="sm" tone="danger"><ResonanceIcon kind="delete" size={14} /></ResonanceActionIcon>清空全部
                </button>
              </div>
            </motion.section>
          </div>
        </div>

        <Modal
          open={exportTarget !== null}
          onClose={closeExportDialog}
          closeDisabled={exporting}
          className="max-w-md border-white/[0.1] bg-[#242424]"
          labelledBy="export-dialog-title"
        >
          {exportTarget ? <>
            <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
              <div className="flex items-start gap-3">
                <div className="mt-0.5 rounded-md bg-[#8fc8be]/10 p-2 text-[#8fc8be]"><ResonanceIcon kind="download" size={19} /></div>
                <div>
                  <h2 id="export-dialog-title" className="text-base font-medium text-tide">导出抽卡记录</h2>
                  <p className="mt-1 text-xs text-wave">UID {displayUid(exportTarget.playerId)}</p>
                </div>
              </div>
              <ResonanceCloseButton onClick={closeExportDialog} disabled={exporting} />
            </div>
            <div className="space-y-4 p-5">
              <div className="grid grid-cols-2 rounded-md border border-white/[0.07] bg-white/[0.025] p-0.5">
                {(['all', 'custom'] as const).map((mode) => (
                  <button type="button" key={mode} onClick={() => setExportMode(mode)} className={`rounded px-3 py-2 text-xs ${exportMode === mode ? 'bg-white/[0.09] text-tide' : 'text-wave hover:text-tide'}`}>
                    {mode === 'all' ? '全部记录' : '指定时间'}
                  </button>
                ))}
              </div>
              {exportMode === 'custom' ? (
                <div className="grid grid-cols-2 gap-3">
                  <div><span className="mb-1.5 block text-[10px] text-wave">开始日期</span><ThemedDateInput value={exportStartDate} min={exportTarget.earliestDate} max={exportEndDate || exportTarget.latestDate} onChange={setExportStartDate} label="导出开始日期" className="h-9 px-3 text-xs" /></div>
                  <div><span className="mb-1.5 block text-[10px] text-wave">结束日期</span><ThemedDateInput value={exportEndDate} min={exportStartDate || exportTarget.earliestDate} max={exportTarget.latestDate} onChange={setExportEndDate} label="导出结束日期" className="h-9 px-3 text-xs" /></div>
                  <p className={`col-span-2 text-[10px] ${exportStartDate && exportEndDate && exportStartDate <= exportEndDate ? 'text-wave' : 'text-[#d99a9a]'}`}>
                    {exportStartDate && exportEndDate && exportStartDate <= exportEndDate ? `将导出 ${exportStartDate} 至 ${exportEndDate} 的记录（含首尾两天）` : '请选择有效日期范围'}
                  </p>
                </div>
              ) : (
                <p className="text-xs leading-5 text-wave">导出该 UID 当前保存的全部抽卡记录，文件格式与 JSON 导入兼容。</p>
              )}
              <div className="flex justify-end gap-2 pt-1">
                <button type="button" onClick={closeExportDialog} disabled={exporting} className="px-4 py-2 text-sm text-wave hover:text-tide disabled:opacity-40">取消</button>
                <button type="button" onClick={() => void handleExport()} disabled={exporting || (exportMode === 'custom' && (!exportStartDate || !exportEndDate || exportStartDate > exportEndDate))} className="tide-btn flex items-center gap-2 px-4 py-2 text-sm disabled:opacity-40">
                  {exporting ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind="download" size={13} />}
                  {exporting ? '导出中' : '选择位置并导出'}
                </button>
              </div>
            </div>
          </> : null}
        </Modal>

        <Modal
          open={deleteTarget !== null}
          onClose={closeDeleteDialog}
          closeDisabled={deleting}
          className="max-w-md border-[#d84848]/30 bg-[#242424]"
          labelledBy="delete-dialog-title"
        >
            {deleteTarget && <>
              <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 rounded-md bg-[#d84848]/10 p-2 text-[#d99a9a]"><ResonanceIcon kind="warning" size={19} /></div>
                  <div>
                    <h2 id="delete-dialog-title" className="text-base font-medium text-tide">
                      {deleteTarget.playerId ? `删除 UID ${displayUid(deleteTarget.playerId)} 的记录` : '清空所有抽卡记录'}
                    </h2>
                    <p className="mt-1 text-xs text-wave">操作前会自动创建完整数据库备份</p>
                  </div>
                </div>
                <ResonanceCloseButton onClick={closeDeleteDialog} disabled={deleting} />
              </div>

              <div className="space-y-4 p-5">
                <div className="grid grid-cols-2 gap-3 border-y border-white/[0.06] py-3 text-sm">
                  <div><div className="text-xs text-wave">记录数量</div><div className="mt-1 font-medium text-tide">{targetRecordCount.toLocaleString()} 条</div></div>
                  <div><div className="text-xs text-wave">涉及玩家</div><div className="mt-1 font-medium text-tide">{deleteTarget.playerId ? 1 : pools.length} 位</div></div>
                  {targetMeta.recordRange && (
                    <div className="col-span-2">
                      <div className="text-xs text-wave">记录范围</div>
                      <div className="mt-1 flex items-center gap-1.5 text-tide">
                        <ResonanceIcon kind="database" size={12} className="text-[#8fc8be]" />
                        {targetMeta.recordRange}
                      </div>
                    </div>
                  )}
                  {targetMeta.hasImport && (
                    <div className="col-span-2">
                      <div className="text-xs text-wave">最近同步</div>
                      <div className="mt-1 flex flex-wrap items-center gap-1.5 text-tide">
                        <ResonanceIcon kind="sync" size={12} className="text-[#c9ab78]" />
                        <span className="tabular-nums">{targetMeta.lastImportedAt}</span>
                        {targetMeta.impInferred && (
                          <span className="inline-flex items-center gap-1 rounded border border-[#c9ab78]/25 bg-[#c9ab78]/[0.08] px-1.5 py-px text-[10px] text-[#c9ab78]" title="升级前已导入数据，同步时间由记录范围推断">
                            <ResonanceIcon kind="info" size={10} /> 推断
                          </span>
                        )}
                      </div>
                    </div>
                  )}
                </div>

                <label className="block">
                  <span className="mb-2 block text-xs text-wave">输入 <span className="font-medium text-[#d99a9a]">{expectedConfirmation}</span> 确认删除</span>
                  <input autoFocus value={confirmationText} onChange={(event) => setConfirmationText(event.target.value)} className="glass-input w-full px-3 py-2 text-sm" />
                </label>

                <div className="flex justify-end gap-2 pt-1">
                  <button onClick={closeDeleteDialog} disabled={deleting} className="px-4 py-2 text-sm text-wave hover:text-tide disabled:opacity-40">取消</button>
                  <button
                    onClick={handleConfirmDelete}
                    disabled={deleting || confirmationText !== expectedConfirmation}
                    className="flex items-center gap-2 rounded-md bg-[#a64f4f] px-4 py-2 text-sm text-white hover:bg-[#b85a5a] disabled:cursor-not-allowed disabled:opacity-35"
                  >
                    <ResonanceActionIcon size="sm" tone="danger">{deleting ? <LoaderCircle size={11} className="animate-spin" /> : <ResonanceIcon kind="delete" size={12} />}</ResonanceActionIcon>
                    {deleting ? '备份并删除中' : '备份并删除'}
                  </button>
                </div>
              </div>
            </>}
        </Modal>

        <Modal
          open={boundaryPlayerId !== null && boundaryConfirmation === null}
          onClose={() => { setBoundaryPlayerId(null); setBoundaryConfirmation(null); }}
          closeDisabled={boundarySaving}
          className="max-w-2xl border-white/[0.08] bg-[#242424]"
          labelledBy="boundary-management-dialog-title"
        >
          {boundaryPlayerId && boundaryStatuses[boundaryPlayerId] && <>
              <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 rounded-md bg-[#c9ab78]/10 p-2 text-[#c9ab78]"><ResonanceIcon kind="database" size={19} /></div>
                  <div>
                    <h2 id="boundary-management-dialog-title" className="text-base font-medium text-tide">卡池历史起点</h2>
                    <p className="mt-1 text-xs text-wave">UID {displayUid(boundaryPlayerId)}</p>
                  </div>
                </div>
                <ResonanceCloseButton onClick={() => setBoundaryPlayerId(null)} disabled={boundarySaving} />
              </div>

              <div className="max-h-[65vh] space-y-4 overflow-y-auto p-5">
                <p className="text-xs leading-5 text-wave">若确认首条记录前不存在更早垫抽，可将该卡池现存记录认定为完整起点。</p>
                <section>
                  <div className="divide-y divide-white/[0.05] overflow-hidden rounded-md border border-white/[0.06]">
                    {boundaryStatuses[boundaryPlayerId].map((boundary) => {
                      const isBoundaryHighlightTarget = highlightedBoundaryPoolType === boundary.pool_type;
                      return (
                      <div key={boundary.pool_type} className="flex items-center justify-between gap-4 px-3 py-3">
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2 text-xs text-tide">
                            <span>{boundary.pool_name}</span>
                            <span className={`rounded border px-1.5 py-px text-[9px] ${boundary.confirmed ? 'border-[#6faaa0]/20 text-[#8fc8be]' : 'border-[#c9ab78]/20 text-[#c9ab78]'}`}>
                              {boundary.confirmed ? '起点已确认' : '首段为下界'}
                            </span>
                          </div>
                          <p className="mt-1 text-[10px] leading-4 text-wave">
                            首个五星 {boundary.first_five_star_name} · {boundary.first_five_star_time.slice(0, 10)} · 可见 {boundary.visible_pulls} 抽
                            {!boundary.confirmed && '，当前不参与完整区间统计'}
                          </p>
                        </div>
                        <motion.button
                          key={`${boundary.pool_type}-${isBoundaryHighlightTarget ? 'highlight' : 'normal'}`}
                          onClick={() => { setCompletionPulls(''); setBoundaryConfirmation(boundary); }}
                          animate={isBoundaryHighlightTarget ? (fadingBoundaryHighlight ? {
                            borderColor: 'rgba(255,255,255,0)',
                            backgroundColor: 'rgba(0,0,0,0)',
                            color: '#9b9d9b',
                            boxShadow: '0 0 0 rgba(0,0,0,0)',
                          } : {
                            borderColor: ['rgba(216,189,132,0.35)', 'rgba(216,189,132,0.9)', 'rgba(216,189,132,0.35)'],
                            backgroundColor: ['rgba(216,189,132,0.06)', 'rgba(216,189,132,0.18)', 'rgba(216,189,132,0.06)'],
                            color: ['#d8bd84', '#f0d9a7', '#d8bd84'],
                            boxShadow: ['0 0 0 1px rgba(216,189,132,0.08)', '0 0 0 4px rgba(216,189,132,0.18)', '0 0 0 1px rgba(216,189,132,0.08)'],
                          }) : undefined}
                          transition={isBoundaryHighlightTarget
                            ? fadingBoundaryHighlight
                              ? { duration: 0.7, ease: 'easeOut' }
                              : { duration: 1.8, repeat: Infinity, ease: 'linear' }
                            : undefined}
                          className="shrink-0 rounded-md border border-transparent px-2.5 py-1.5 text-[10px] text-wave transition-colors hover:border-white/[0.14] hover:text-tide"
                        >
                          {boundary.confirmed ? '撤销确认' : '确认起点'}
                        </motion.button>
                      </div>
                      );
                    })}
                  </div>
                </section>
                <p className="text-[10px] leading-5 text-wave">确认只影响边界标记与统计口径，不会修改、补造或删除记录；以后导入更早记录时会自动失效。</p>
              </div>
            </>}
        </Modal>

        <Modal
          open={boundaryConfirmation !== null}
          onClose={() => setBoundaryConfirmation(null)}
          closeDisabled={boundarySaving}
          className="max-w-md border-[#c9ab78]/20 bg-[#242424]"
          labelledBy="boundary-dialog-title"
        >
          {boundaryConfirmation && <>
            <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
              <div>
                <h2 id="boundary-dialog-title" className="text-base font-medium text-tide">
                  {boundaryConfirmation.confirmed ? '撤销历史起点确认' : '确认现存记录为完整起点'}
                </h2>
                <p className="mt-1 text-xs text-wave">{boundaryConfirmation.pool_name}</p>
              </div>
              <ResonanceCloseButton onClick={() => setBoundaryConfirmation(null)} disabled={boundarySaving} />
            </div>
            <div className="space-y-4 p-5 text-xs leading-5 text-wave">
              {boundaryConfirmation.confirmed ? (
                <p>撤销后，首页和记录页会重新将首个五星显示为 <span className="text-[#c9ab78]">≥{boundaryConfirmation.original_visible_pulls} 抽</span>，记录页恢复边界提示，并从完整区间、平均值和概率分布中排除。原始记录不会改变。</p>
              ) : (
                <>
                  <p>仅当你确定该卡池开放以来的记录已经完整覆盖，且首条记录之前不存在垫抽时再确认。</p>
                  <div className="rounded-md border border-[#c9ab78]/15 bg-[#c9ab78]/[0.04] px-3 py-2.5 text-[#d9c28f]">
                    确认后，首个五星将按 {boundaryConfirmation.visible_pulls} 抽纳入首页和分析统计；首页、记录页不再显示 ≥，记录页也不再显示该卡池的边界提示。
                  </div>
                  <p>以后导入更早记录时，本次确认会自动失效并恢复边界提示。</p>
                  <div className="rounded-md border border-[#8fc8be]/15 bg-[#8fc8be]/[0.04] px-3 py-3">
                    <p className="text-[#b8d8d1]">如果你知道首个五星的实际抽数，可补足缺失的三星和四星记录。</p>
                    <div className="mt-2 flex items-center gap-2">
                      <label className="text-[11px] text-wave" htmlFor="boundary-target-pulls">实际抽数</label>
                      <input id="boundary-target-pulls" value={completionPulls} placeholder="如 59" onChange={(event) => setCompletionPulls(event.target.value.replace(/\D/g, '').slice(0, 2))} className="glass-input h-8 w-20 px-2 text-xs tabular-nums text-tide" inputMode="numeric" />
                      <button onClick={handleBoundaryCompletion} disabled={boundarySaving} className="tide-btn h-8 px-3 text-xs disabled:opacity-40">补足缺失记录</button>
                    </div>
                    <p className="mt-2 text-[10px] text-wave">现有可见 {boundaryConfirmation.visible_pulls} 抽，将新增目标抽数与可见抽数之差；原始五星记录不会修改。</p>
                  </div>
                </>
              )}
              <div className="flex justify-end gap-2 pt-1">
                <button onClick={() => setBoundaryConfirmation(null)} disabled={boundarySaving} className="px-4 py-2 text-sm text-wave hover:text-tide">取消</button>
                <button onClick={handleBoundaryConfirmation} disabled={boundarySaving} className="tide-btn flex items-center gap-2 px-4 py-2 text-sm disabled:opacity-40">
                  {boundarySaving && <LoaderCircle size={12} className="animate-spin" />}
                  {boundaryConfirmation.confirmed ? '确认撤销' : completionPulls.trim() !== '' ? '确认并补足' : '确认完整起点'}
                </button>
              </div>
            </div>
          </>}
        </Modal>

        <Modal
          open={updateInfo !== null}
          onClose={closeUpdateModal}
          closeDisabled={updating}
          className="max-w-md border-white/[0.08] bg-[#242424]"
          labelledBy="update-dialog-title"
        >
            {updateInfo && <>
              <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 rounded-md bg-[#6faaa0]/10 p-2 text-[#8fc8be]"><ResonanceIcon kind="refresh" size={19} /></div>
                  <div>
                    <h2 id="update-dialog-title" className="text-base font-medium text-tide">发现新版本</h2>
                    <p className="mt-1 text-xs text-wave">v{appVersion} → v{updateInfo.version}</p>
                  </div>
                </div>
                <ResonanceCloseButton onClick={closeUpdateModal} disabled={updating} />
              </div>

              <div className="p-5">
                {updateInfo.body && (
                  <div className="update-notes mb-4 max-h-60 overflow-y-auto rounded-md border border-white/[0.06] bg-white/[0.02] p-3 text-xs leading-5 text-wave">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{stripUpdateNotesFooter(updateInfo.body)}</ReactMarkdown>
                  </div>
                )}

                {updating && (
                  <div className="mb-4">
                    <div className="mb-1.5 flex items-center justify-between text-[11px] text-wave">
                      <span>{updateProgress < 100 ? '下载中' : '安装中'}...</span>
                      <span>{updateProgress}%</span>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-white/[0.06]">
                      <div className="h-full rounded-full bg-[#6faaa0] transition-all" style={{ width: `${updateProgress}%` }} />
                    </div>
                  </div>
                )}

                <div className="flex justify-end gap-2 pt-1">
                  <button onClick={closeUpdateModal} disabled={updating} className="px-4 py-2 text-sm text-wave hover:text-tide disabled:opacity-40">以后再说</button>
                  <button
                    onClick={handleInstallUpdate}
                    disabled={updating}
                    className="flex items-center gap-2 rounded-md bg-[#5a8a82] px-4 py-2 text-sm text-white hover:bg-[#6a9a92] disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <ResonanceActionIcon size="sm" tone="gold">{updating ? <LoaderCircle size={11} className="animate-spin" /> : <ResonanceIcon kind="download" size={12} />}</ResonanceActionIcon>
                    {updating ? '更新中' : '立即更新'}
                  </button>
                </div>
              </div>
            </>}
        </Modal>
      </div>
    </PageTransition>
  );
}
