import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { open as openDialog, save } from '@tauri-apps/plugin-dialog';
import { open as openUrl } from '@tauri-apps/plugin-shell';
import { type Update } from '@tauri-apps/plugin-updater';
import { listen } from '@tauri-apps/api/event';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useUpdateStore } from '../store/useUpdateStore';
import {
  LoaderCircle,
} from 'lucide-react';
import { getVersion } from '@tauri-apps/api/app';
import PageTransition from '../components/PageTransition';
import PageSignalField from '../components/PageSignalField';
import Modal from '../components/Modal';
import ResonanceCloseButton from '../components/ResonanceCloseButton';
import ResonanceActionIcon from '../components/ResonanceActionIcon';
import ResonanceIcon from '../components/ResonanceModeIcon';
import ResonanceEmptyState from '../components/ResonanceEmptyState';
import { useUiFeedback } from '../hooks/useUiFeedback';
import { playUiFeedback } from '../lib/uiFeedback';
import { gachaApi } from '../services/tauri-api';
import { useGachaStore } from '../store/useGachaStore';
import {
  getSyncFreshness,
  daysSince,
  SYNC_WARN_DAYS,
  SYNC_DANGER_DAYS,
  type SyncFreshness,
} from '../lib/utils';
import type { GameDirValidation, RecordSummary } from '../types';

type DeleteTarget = { playerId: string | null };

// 去除 release notes 末尾由模板自动生成的下载提示和自动生成标记
// 这些内容在 GitHub Release 页面有意义，但出现在更新弹窗中不合适
function stripUpdateNotesFooter(body: string): string {
  const markers = ['下载文件见下方 Assets', 'Auto-generated by GitHub Actions'];
  const lines = body.split('\n').filter((line) => !markers.some((m) => line.includes(m)));
  // 去除因移除尾部内容而残留的 --- 分隔线和多余空行
  let result = lines.join('\n').replace(/\n+$/, '');
  result = result.replace(/---\s*$/, '').replace(/\n+$/, '');
  return result;
}

export default function SettingsPage() {
  const { settings, fetchSettings, saveGameDir, clearRecords, pools, addToast, summaries: storeSummaries, fetchSummaries } = useGachaStore();
  const [gameDirInput, setGameDirInput] = useState('');
  const [saving, setSaving] = useState(false);
  const [validating, setValidating] = useState(false);
  const [validation, setValidation] = useState<GameDirValidation | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(pools.length > 0 && storeSummaries.length === 0);
  const [summaryError, setSummaryError] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null);
  const [confirmationText, setConfirmationText] = useState('');
  const [deleting, setDeleting] = useState(false);
  const [lastBackupPath, setLastBackupPath] = useState<string | null>(null);
  const [updateInfo, setUpdateInfo] = useState<Update | null>(null);
  const { availableUpdate, checking: checkingUpdate, manualCheck } = useUpdateStore();
  const [updating, setUpdating] = useState(false);
  const [updateProgress, setUpdateProgress] = useState(0);
  const [appVersion, setAppVersion] = useState('');
  const { enabled: soundEnabled, setEnabled: setSoundEnabled } = useUiFeedback();

  useEffect(() => {
    fetchSettings();
  }, []);

  useEffect(() => {
    getVersion().then(setAppVersion).catch(() => {});
  }, []);

  useEffect(() => {
    if (settings) setGameDirInput(settings.game_dir);
  }, [settings]);

  useEffect(() => {
    const path = gameDirInput.trim();
    if (!path) {
      setValidation(null);
      setValidating(false);
      return;
    }

    let cancelled = false;
    setValidating(true);
    const timer = window.setTimeout(async () => {
      try {
        const result = await gachaApi.validateGameDir(path);
        if (!cancelled) setValidation(result);
      } catch {
        if (!cancelled) {
          setValidation({ valid: false, log_path: '', message: '目录校验失败，请重新选择' });
        }
      } finally {
        if (!cancelled) setValidating(false);
      }
    }, 300);

    return () => {
      cancelled = true;
      window.clearTimeout(timer);
    };
  }, [gameDirInput]);

  // 订阅 store.summaries；进入设置页时确保拉取过一次（有 pools 但 summaries 空时触发）
  useEffect(() => {
    if (pools.length === 0) {
      setSummaryLoading(false);
      setSummaryError(false);
      return;
    }
    if (storeSummaries.length > 0) {
      setSummaryLoading(false);
      setSummaryError(false);
      return;
    }
    let cancelled = false;
    setSummaryLoading(true);
    setSummaryError(false);
    fetchSummaries()
      .then(() => {
        if (!cancelled) setSummaryLoading(false);
      })
      .catch(() => {
        if (!cancelled) {
          setSummaryError(true);
          setSummaryLoading(false);
        }
      });
    return () => { cancelled = true; };
  }, [pools, storeSummaries.length, fetchSummaries]);

  // 直接用 store 的 summaries，保证删除/清空/新增玩家后立即同步
  const summaries = storeSummaries;

  const summaryByPlayer = useMemo(
    () => new Map(summaries.map((summary) => [summary.player_id, summary])),
    [summaries],
  );
  const totalRecords = summaries.reduce((sum, summary) => sum + summary.record_count, 0);
  const savedPath = settings?.game_dir.trim() ?? '';
  const isDirty = gameDirInput.trim() !== savedPath;
  const directoryState = !gameDirInput.trim()
    ? { label: '未配置', tone: 'idle' }
    : validating
      ? { label: '校验中', tone: 'checking' }
      : validation?.valid
        ? { label: '目录可用', tone: 'ready' }
        : { label: '需要检查', tone: 'error' };

  const selectedSummary = deleteTarget?.playerId ? summaryByPlayer.get(deleteTarget.playerId) : null;
  const expectedConfirmation = deleteTarget?.playerId ?? '清空全部数据';
  const targetRecordCount = deleteTarget?.playerId ? selectedSummary?.record_count ?? 0 : totalRecords;

  // 展示用的辅助函数：每个玩家 → 记录范围（完整日期段） + 最近同步时间（单点）
  const formatSummaryMeta = (summary: RecordSummary | undefined) => {
    if (!summary) return { recordRange: '', lastImportedAt: '', hasImport: false, impInferred: false };
    const recordRange = `${summary.earliest_time.slice(0, 10)} 至 ${summary.latest_time.slice(0, 10)}`;
    const hasImport = Boolean(summary.last_imported_at);
    const lastImportedAt = hasImport ? summary.last_imported_at!.slice(0, 10) : '';
    return {
      recordRange,
      lastImportedAt,
      hasImport,
      impInferred: summary.is_inferred === true,
    };
  };

  // 清空全部时聚合所有玩家的记录范围和最近同步时间
  const overallMeta = useMemo(() => {
    if (summaries.length === 0) return { recordRange: '', lastImportedAt: '', hasImport: false, impInferred: false };
    const earliestRecord = summaries.reduce((min, item) => (item.earliest_time < min ? item.earliest_time : min), summaries[0].earliest_time);
    const latestRecord = summaries.reduce((max, item) => (item.latest_time > max ? item.latest_time : max), summaries[0].latest_time);
    const lastImported = summaries
      .filter((item) => item.last_imported_at)
      .map((item) => item.last_imported_at!)
      .reduce((max, t) => (t > max ? t : max), '');
    return {
      recordRange: `${earliestRecord.slice(0, 10)} 至 ${latestRecord.slice(0, 10)}`,
      lastImportedAt: lastImported ? lastImported.slice(0, 10) : '',
      hasImport: Boolean(lastImported),
      impInferred: summaries.every((item) => item.is_inferred === true),
    };
  }, [summaries]);

  const targetMeta = selectedSummary ? formatSummaryMeta(selectedSummary) : overallMeta;

  // 玩家 freshness 分级（warn: 120~180 天久未同步 / danger: >180 天可能缺数据）
  const freshnessInfo = useMemo(() => {
    const map = new Map<string, { freshness: SyncFreshness; daysAgo: number }>();
    summaries.forEach((summary) => {
      const freshness = getSyncFreshness(summary.last_imported_at, summary.is_inferred);
      const daysAgo = summary.last_imported_at ? daysSince(summary.last_imported_at) : 0;
      map.set(summary.player_id, { freshness, daysAgo });
    });
    return map;
  }, [summaries]);

  // 是否有任何一个玩家处于 warn 或 danger（用来切换顶部提示条的颜色）
  const anyWarn = useMemo(
    () => summaries.some((summary) => getSyncFreshness(summary.last_imported_at, summary.is_inferred) === 'warn'),
    [summaries],
  );
  const anyDanger = useMemo(
    () => summaries.some((summary) => getSyncFreshness(summary.last_imported_at, summary.is_inferred) === 'danger'),
    [summaries],
  );
  const anyStale = anyWarn || anyDanger;

  const staleCardTip = (freshness: SyncFreshness, daysAgo: number) => {
    if (freshness === 'danger') {
      return `距上次同步已 ${daysAgo} 天（超过 ${SYNC_DANGER_DAYS} 天阈值）。官方链接通常只保留近 6 个月，这段时间可能已存在数据遗漏（若期间未抽卡则不会丢数据）。`;
    }
    return `距上次同步已 ${daysAgo} 天（超过 ${SYNC_WARN_DAYS} 天阈值）。建议尽快同步以免丢失 6 个月临界区的缺口。`;
  };

  const handleSelectFolder = async () => {
    try {
      const selected = await openDialog({ directory: true, multiple: false, title: '选择鸣潮游戏目录' });
      if (selected) setGameDirInput(selected);
    } catch {
      addToast('error', '无法打开目录选择器');
    }
  };

  const handleSave = async () => {
    if (!isDirty || !validation?.valid) return;
    setSaving(true);
    try {
      await saveGameDir(gameDirInput.trim());
    } catch {
      // Store 已显示失败提示。
    } finally {
      setSaving(false);
    }
  };

  const openDeleteDialog = (playerId: string | null) => {
    setConfirmationText('');
    setDeleteTarget({ playerId });
  };

  const closeDeleteDialog = () => {
    if (deleting) return;
    setDeleteTarget(null);
    setConfirmationText('');
  };

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    const result = await clearRecords(deleteTarget.playerId ?? undefined);
    setDeleting(false);
    if (!result) return;
    setLastBackupPath(result.backup_path);
    setDeleteTarget(null);
    setConfirmationText('');
  };

  const copyBackupPath = async () => {
    if (!lastBackupPath) return;
    try {
      await navigator.clipboard.writeText(lastBackupPath);
      addToast('success', '备份路径已复制');
    } catch {
      addToast('error', '复制失败');
    }
  };

  const openBackupDirectory = async () => {
    try {
      await gachaApi.openBackupDirectory();
    } catch (error) {
      addToast('error', `无法打开备份目录: ${String(error)}`);
    }
  };

  const handleExport = async (playerId: string) => {
    try {
      const today = new Date().toISOString().slice(0, 10);
      const path = await save({
        defaultPath: `uid_${playerId}_${today}.json`,
        filters: [{ name: 'JSON', extensions: ['json'] }],
      });
      if (!path) return;
      await gachaApi.exportGachaJson(playerId, path);
      addToast('success', '导出成功');
    } catch (e) {
      addToast('error', `导出失败: ${String(e)}`);
    }
  };

  const handleCheckUpdate = async () => {
    try {
      const update = await manualCheck();
      if (update) {
        setUpdateInfo(update);
      } else {
        addToast('success', '已是最新版本');
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      addToast('error', `检查更新失败: ${msg}`);
    }
  };

  const handleInstallUpdate = async () => {
    if (!updateInfo) return;
    setUpdating(true);
    setUpdateProgress(0);

    const unlistenFns: Array<() => void> = [];
    const lastProxyRef = { current: '' };
    try {
      const platforms = (updateInfo.rawJson.platforms ?? {}) as Record<string, { url?: string; signature?: string }>;
      const ua = navigator.userAgent.toLowerCase();
      const platformKey = ua.includes('win')
        ? 'windows-x86_64'
        : ua.includes('mac')
          ? (navigator.userAgent.includes('aarch64') || navigator.userAgent.includes('arm64') ? 'darwin-aarch64' : 'darwin-x86_64')
          : 'linux-x86_64';
      const info = platforms[platformKey];
      const officialUrl = info?.url;
      if (!officialUrl) throw new Error('latest.json 未包含安装包下载地址');

      // 注册进度事件（仅代理切换时提示一次）
      const unlistenProgress = await listen<{ proxy: string; percent: number }>(
        'update-download-progress',
        (event) => {
          const { proxy, percent } = event.payload;
          if (proxy !== lastProxyRef.current) {
            lastProxyRef.current = proxy;
            addToast('info', `通过 ${proxy} 下载中...`);
          }
          setUpdateProgress(percent);
        },
      );
      unlistenFns.push(unlistenProgress);

      const unlistenDone = await listen<{ path: string }>(
        'update-download-done',
        () => {
          addToast('success', '下载完成，正在安装...');
        },
      );
      unlistenFns.push(unlistenDone);

      await gachaApi.downloadAndInstallUpdate(officialUrl, updateInfo.version);
      setUpdateProgress(100);

      // 给前端一点时间渲染完成态，然后由 NSIS 静默安装并退出当前应用
      await new Promise((resolve) => window.setTimeout(resolve, 800));
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      addToast('error', `更新失败: ${msg}`);
      setUpdating(false);
    } finally {
      unlistenFns.forEach((fn) => fn());
    }
  };

  const closeUpdateModal = () => {
    if (updating) return;
    setUpdateInfo(null);
    setUpdateProgress(0);
  };

  const handleOpenLogDirectory = async () => {
    try {
      await gachaApi.openLogDirectory();
    } catch (error) {
      addToast('error', `打开日志目录失败: ${String(error)}`);
    }
  };

  return (
    <PageTransition>
      <div className="page-scroll h-full overflow-y-auto overflow-x-hidden">
        <div className="page-container settings-page-container w-full space-y-5 p-6">
          <header className="page-header settings-page-header py-1">
            <PageSignalField variant="settings" />
            <h1 className="page-title text-xl font-semibold text-tide">设置</h1>
            <p className="page-subtitle mt-1 text-xs text-wave">管理扫描目录与本地数据</p>
          </header>

          <div className="settings-console-grid grid items-start gap-4 md:grid-cols-[minmax(0,0.9fr)_minmax(360px,1.1fr)]">
            <div className="space-y-4">
              <motion.section
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                className="resonance-panel settings-panel settings-control-panel settings-directory-panel p-5"
              >
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2 text-sm font-medium text-tide">
                    <ResonanceActionIcon tone="gold"><ResonanceIcon kind="directory" size={15} /></ResonanceActionIcon>游戏目录
                  </div>
                  <div className="settings-state-readout" data-state={directoryState.tone}>
                    <span className="settings-state-pulse" />
                    <span>{directoryState.label}</span>
                  </div>
                </div>
                <p className="mt-1 text-xs text-wave">扫描抽卡记录时读取此目录中的 Client.log</p>

                <label className="mt-5 block">
                  <span className="mb-2 block text-xs text-wave">安装目录</span>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={gameDirInput}
                      onChange={(event) => setGameDirInput(event.target.value)}
                      placeholder="例如: E:\Wuthering Waves\Wuthering Waves"
                      className="glass-input min-w-0 flex-1 px-3 py-2.5 text-sm"
                    />
                    <button onClick={handleSelectFolder} className="glass-input flex shrink-0 items-center gap-2 px-3 py-2.5 text-sm text-wave hover:text-tide">
                      <ResonanceActionIcon size="sm"><ResonanceIcon kind="directory" size={14} /></ResonanceActionIcon>选择
                    </button>
                  </div>
                </label>

                <div className="mt-2 min-h-5">
                  {!gameDirInput.trim() ? (
                    <div className="flex items-center gap-2 text-[11px] text-wave"><ResonanceIcon kind="info" size={13} />尚未设置游戏目录</div>
                  ) : validating ? (
                    <div className="flex items-center gap-2 text-[11px] text-wave"><LoaderCircle size={12} className="animate-spin" />正在检查 Client.log</div>
                  ) : validation?.valid ? (
                    <div className="flex items-center gap-2 text-[11px] text-[#8fc8be]"><ResonanceIcon kind="success" size={13} />{validation.message}</div>
                  ) : (
                    <div className="flex items-center gap-2 text-[11px] text-[#d99a9a]"><ResonanceIcon kind="error" size={13} />{validation?.message}</div>
                  )}
                </div>

                <div className="mt-4 flex items-center gap-3">
                  <button
                    onClick={handleSave}
                    disabled={saving || validating || !isDirty || !validation?.valid}
                    className="tide-btn flex items-center gap-2 px-4 py-2 text-sm disabled:opacity-40"
                  >
                    <ResonanceActionIcon size="sm" tone="gold">
                      {saving ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind="save" size={14} />}
                    </ResonanceActionIcon>
                    {saving ? '保存中' : '保存目录'}
                  </button>
                  {isDirty && validation?.valid && <span className="text-[11px] text-[#c9ab78]">有未保存的修改</span>}
                  {!isDirty && savedPath && <span className="text-[11px] text-wave">当前设置已保存</span>}
                </div>
              </motion.section>

              <section className="feedback-preference-row">
                <div className="flex min-w-0 items-center gap-3">
                  <span className="feedback-preference-icon"><ResonanceIcon kind="activity" size={16} /></span>
                  <div className="min-w-0">
                    <div className="text-xs font-medium text-tide">频率反馈</div>
                    <div className="mt-0.5 text-[11px] text-wave">扫描、导入和插入记录完成时播放轻提示音</div>
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <button type="button" onClick={() => void playUiFeedback('record-inserted')} disabled={!soundEnabled} className="feedback-preview-button">试听</button>
                  <button
                    type="button"
                    role="switch"
                    aria-checked={soundEnabled}
                    aria-label="频率反馈"
                    onClick={() => {
                      const next = !soundEnabled;
                      setSoundEnabled(next);
                      if (next) void playUiFeedback('scan-complete');
                    }}
                    className="resonance-toggle"
                    data-active={soundEnabled ? 'true' : 'false'}
                  >
                    <span className="resonance-toggle-track" />
                    <span className="resonance-toggle-node" />
                  </button>
                </div>
              </section>

              <section className="border-t border-white/[0.06] px-1 pt-4 text-xs text-wave">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-tide-dim">Wuwa Gacha Tool v{appVersion}</span>
                    {availableUpdate && !updateInfo && (
                      <span className="rounded-sm bg-[#6faaa0]/10 px-1.5 py-0.5 text-[10px] text-[#8fc8be]">
                        有新版本 v{availableUpdate.version}
                      </span>
                    )}
                  </div>
                  <button
                    onClick={handleCheckUpdate}
                    disabled={checkingUpdate}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide disabled:opacity-50"
                  >
                    <ResonanceActionIcon size="sm">
                      {checkingUpdate ? <LoaderCircle size={12} className="animate-spin" /> : <ResonanceIcon kind="refresh" size={15} />}
                    </ResonanceActionIcon>
                    {checkingUpdate ? '检查中' : '检查更新'}
                  </button>
                </div>
                <p className="mt-2 leading-5">数据仅保存在本机，不会上传到服务器。</p>
                <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2">
                  <button
                    onClick={handleOpenLogDirectory}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide"
                  >
                    <ResonanceActionIcon size="sm"><ResonanceIcon kind="log" size={14} /></ResonanceActionIcon>打开日志目录
                  </button>
                  <button
                    onClick={() => void openUrl('https://github.com/juliy819/wuwa-gacha-tool')}
                    className="flex items-center gap-1.5 text-wave transition-colors hover:text-tide"
                  >
                    <ResonanceActionIcon size="sm"><ResonanceIcon kind="repository" size={14} /></ResonanceActionIcon>GitHub 仓库
                  </button>
                </div>
              </section>
            </div>

            <motion.section
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.05 }}
              className="resonance-panel settings-panel settings-control-panel settings-data-panel p-5"
            >
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 text-sm font-medium text-tide"><ResonanceActionIcon tone="gold"><ResonanceIcon kind="database" size={15} /></ResonanceActionIcon>本地数据</div>
                  <p className="mt-1 text-xs text-wave">{pools.length} 位玩家 · {totalRecords.toLocaleString()} 条记录</p>
                </div>
                <div className="settings-data-readout" aria-label={`本地共 ${totalRecords.toLocaleString()} 条记录`}>
                  <span className="settings-data-readout-value">{totalRecords.toLocaleString()}</span>
                  <span className="settings-data-readout-label">条记录</span>
                  <span className="settings-data-readout-orbit" aria-hidden="true" />
                </div>
              </div>

              <div
                className={`mt-4 flex items-start gap-2 rounded-md border px-3 py-2.5 text-[11px] leading-5 ${
                  anyDanger
                    ? 'border-[#d84848]/25 bg-[#d84848]/[0.07] text-[#d99a9a]'
                    : anyWarn
                      ? 'border-[#c99a68]/15 bg-[#c99a68]/[0.05] text-[#d9bd9a]'
                      : 'border-[#c9ab78]/15 bg-[#c9ab78]/[0.05] text-[#c9ab78]'
                }`}
              >
                {anyDanger ? (
                  <ResonanceIcon kind="error" size={14} className="mt-0.5 shrink-0 text-[#d84848]" />
                ) : anyWarn ? (
                  <ResonanceIcon kind="warning" size={14} className="mt-0.5 shrink-0 text-[#d09960]" />
                ) : (
                  <ResonanceIcon kind="warning" size={14} className="mt-0.5 shrink-0" />
                )}
                <span>
                  官方抽卡链接仅保留近约 6 个月。建议至少每半年同步一次，超期缺口无法自动补回。
                  {anyDanger && (
                    <span className="ml-2 text-[#d84848]">（检测到超过 {SYNC_DANGER_DAYS} 天未同步，可能已存在数据遗漏）</span>
                  )}
                  {!anyDanger && anyWarn && (
                    <span className="ml-2 text-[#d09960]">（检测到超过 {SYNC_WARN_DAYS} 天未同步，建议尽快同步）</span>
                  )}
                </span>
              </div>

              {lastBackupPath && (
                <div className="mt-3 flex items-center gap-3 rounded-md border border-[#6faaa0]/15 bg-[#6faaa0]/[0.05] px-3 py-2.5">
                  <ResonanceIcon kind="success" size={15} className="shrink-0 text-[#8fc8be]" />
                  <div className="min-w-0 flex-1">
                    <div className="text-[11px] text-[#8fc8be]">删除前备份已创建</div>
                    <div className="mt-0.5 truncate text-[10px] text-wave" title={lastBackupPath}>{lastBackupPath}</div>
                  </div>
                  <button onClick={() => void openBackupDirectory()} className="flex h-7 shrink-0 items-center gap-1 rounded-md px-2 text-[10px] text-wave hover:bg-white/[0.05] hover:text-tide" title="打开备份目录"><ResonanceIcon kind="directory" size={12} />目录</button>
                  <button onClick={copyBackupPath} className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-wave hover:bg-white/[0.05] hover:text-tide" title="复制备份路径"><ResonanceActionIcon size="sm"><ResonanceIcon kind="copy" size={12} /></ResonanceActionIcon></button>
                </div>
              )}

              <div className="mt-4 overflow-hidden rounded-md border border-white/[0.06]">
                {summaryLoading ? (
                  <div className="flex items-center justify-center gap-2 py-10 text-xs text-wave"><LoaderCircle size={14} className="animate-spin" />正在读取数据摘要</div>
                ) : summaryError ? (
                  <div className="py-10 text-center text-xs text-[#d99a9a]">数据摘要读取失败</div>
                ) : pools.length === 0 ? (
                  <ResonanceEmptyState variant="database" compact title="尚未保存抽卡记录" description="完成一次扫描或导入后，本地数据摘要会显示在这里" />
                ) : (
                  <div className="divide-y divide-white/[0.05]">
                    {pools.map((playerId) => {
                      const summary = summaryByPlayer.get(playerId);
                      const f = freshnessInfo.get(playerId);
                      const freshness = f?.freshness ?? 'fresh';
                      const isWarn = freshness === 'warn';
                      const isDanger = freshness === 'danger';
                      const isStale = isWarn || isDanger;
                      const tip = isStale ? staleCardTip(freshness, f!.daysAgo) : undefined;

                      // 根据 freshness 选配色
                      const palette =
                        isDanger
                          ? {
                              border: 'border-[#d84848]/20',
                              bg: 'bg-[#d84848]/[0.04]',
                              badge: 'border-[#d84848]/25 bg-[#d84848]/[0.08] text-[#d84848]',
                              label: '可能缺数据',
                              icon: 'text-[#d99a9a]',
                            }
                          : isWarn
                            ? {
                                border: 'border-[#c99a68]/20',
                                bg: 'bg-[#c99a68]/[0.04]',
                                badge: 'border-[#c99a68]/25 bg-[#c99a68]/[0.08] text-[#d09960]',
                                label: '久未同步',
                                icon: 'text-[#d9bd9a]',
                              }
                            : null;
                      return (
                        <div
                          key={playerId}
                          className={`relative flex items-center justify-between gap-3 px-3 py-3 ${palette ? palette.bg : ''}`}
                          title={tip}
                        >
                          {palette && (
                            <div className={`pointer-events-none absolute inset-0 rounded-md border ${palette.border}`} />
                          )}
                          <div className="relative min-w-0">
                            <div className="flex items-center gap-1.5">
                              <div className="text-sm text-tide">UID {playerId}</div>
                              {palette && (
                                <span
                                  className={`inline-flex items-center gap-1 rounded border px-1.5 py-px text-[10px] ${palette.badge}`}
                                  title={tip}
                                >
                                  <ResonanceIcon kind={isDanger ? 'error' : 'warning'} size={10} /> {palette.label}
                                </span>
                              )}
                            </div>
                            {summary && (
                              <div className="mt-1 flex flex-col gap-0.5 text-[11px] text-wave">
                                <div className="flex items-center gap-1.5">
                                  <ResonanceIcon kind="database" size={12} className="text-[#8fc8be]" />
                                  <span>记录 {summary.record_count.toLocaleString()} 条 · {summary.earliest_time.slice(0, 10)} 至 {summary.latest_time.slice(0, 10)}</span>
                                </div>
                                {summary.last_imported_at && (
                                  <div className="flex items-center gap-1.5">
                                    <ResonanceIcon
                                      kind="sync"
                                      size={12}
                                      className={palette ? palette.icon : 'text-[#c9ab78]'}
                                    />
                                    <span className={palette ? palette.icon : ''}>
                                      最近同步 {summary.last_imported_at.slice(0, 10)}
                                      {summary.is_inferred && (
                                        <span className="ml-1.5 inline-flex items-center gap-1 rounded border border-[#c9ab78]/25 bg-[#c9ab78]/[0.08] px-1.5 py-px text-[10px] text-[#c9ab78]" title="升级前已导入数据，同步时间由记录范围推断">
                                          <ResonanceIcon kind="info" size={10} /> 推断
                                        </span>
                                      )}
                                    </span>
                                  </div>
                                )}
                              </div>
                            )}
                          </div>
                          <div className="relative flex shrink-0 items-center gap-1">
                            <button onClick={() => handleExport(playerId)} className="flex h-8 w-8 items-center justify-center rounded-md text-wave hover:bg-white/[0.05] hover:text-tide" title={`导出 UID ${playerId} 的数据`}><ResonanceActionIcon size="sm"><ResonanceIcon kind="download" size={14} /></ResonanceActionIcon></button>
                            <button onClick={() => openDeleteDialog(playerId)} className="flex h-8 w-8 items-center justify-center rounded-md text-wave hover:bg-[#d84848]/10 hover:text-[#d99a9a]" title={`删除 UID ${playerId} 的记录`}><ResonanceActionIcon size="sm" tone="danger"><ResonanceIcon kind="delete" size={14} /></ResonanceActionIcon></button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              <div className="mt-4 flex items-center justify-between border-t border-white/[0.05] pt-4">
                <span className="text-[11px] text-wave">删除前会自动备份数据库</span>
                <button
                  onClick={() => openDeleteDialog(null)}
                  disabled={pools.length === 0}
                  className="flex items-center gap-2 rounded-md border border-[#d84848]/25 px-3 py-2 text-xs text-[#d99a9a] hover:bg-[#d84848]/10 disabled:cursor-not-allowed disabled:opacity-30"
                >
                  <ResonanceActionIcon size="sm" tone="danger"><ResonanceIcon kind="delete" size={14} /></ResonanceActionIcon>清空全部
                </button>
              </div>
            </motion.section>
          </div>
        </div>

        <Modal
          open={deleteTarget !== null}
          onClose={closeDeleteDialog}
          closeDisabled={deleting}
          className="max-w-md border-[#d84848]/30 bg-[#242424]"
          labelledBy="delete-dialog-title"
        >
            {deleteTarget && <>
              <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 rounded-md bg-[#d84848]/10 p-2 text-[#d99a9a]"><ResonanceIcon kind="warning" size={19} /></div>
                  <div>
                    <h2 id="delete-dialog-title" className="text-base font-medium text-tide">
                      {deleteTarget.playerId ? `删除 UID ${deleteTarget.playerId} 的记录` : '清空所有抽卡记录'}
                    </h2>
                    <p className="mt-1 text-xs text-wave">操作前会自动创建完整数据库备份</p>
                  </div>
                </div>
                <ResonanceCloseButton onClick={closeDeleteDialog} disabled={deleting} />
              </div>

              <div className="space-y-4 p-5">
                <div className="grid grid-cols-2 gap-3 border-y border-white/[0.06] py-3 text-sm">
                  <div><div className="text-xs text-wave">记录数量</div><div className="mt-1 font-medium text-tide">{targetRecordCount.toLocaleString()} 条</div></div>
                  <div><div className="text-xs text-wave">涉及玩家</div><div className="mt-1 font-medium text-tide">{deleteTarget.playerId ? 1 : pools.length} 位</div></div>
                  {targetMeta.recordRange && (
                    <div className="col-span-2">
                      <div className="text-xs text-wave">记录范围</div>
                      <div className="mt-1 flex items-center gap-1.5 text-tide">
                        <ResonanceIcon kind="database" size={12} className="text-[#8fc8be]" />
                        {targetMeta.recordRange}
                      </div>
                    </div>
                  )}
                  {targetMeta.hasImport && (
                    <div className="col-span-2">
                      <div className="text-xs text-wave">最近同步</div>
                      <div className="mt-1 flex flex-wrap items-center gap-1.5 text-tide">
                        <ResonanceIcon kind="sync" size={12} className="text-[#c9ab78]" />
                        <span className="tabular-nums">{targetMeta.lastImportedAt}</span>
                        {targetMeta.impInferred && (
                          <span className="inline-flex items-center gap-1 rounded border border-[#c9ab78]/25 bg-[#c9ab78]/[0.08] px-1.5 py-px text-[10px] text-[#c9ab78]" title="升级前已导入数据，同步时间由记录范围推断">
                            <ResonanceIcon kind="info" size={10} /> 推断
                          </span>
                        )}
                      </div>
                    </div>
                  )}
                </div>

                <label className="block">
                  <span className="mb-2 block text-xs text-wave">输入 <span className="font-medium text-[#d99a9a]">{expectedConfirmation}</span> 确认删除</span>
                  <input autoFocus value={confirmationText} onChange={(event) => setConfirmationText(event.target.value)} className="glass-input w-full px-3 py-2 text-sm" />
                </label>

                <div className="flex justify-end gap-2 pt-1">
                  <button onClick={closeDeleteDialog} disabled={deleting} className="px-4 py-2 text-sm text-wave hover:text-tide disabled:opacity-40">取消</button>
                  <button
                    onClick={handleConfirmDelete}
                    disabled={deleting || confirmationText !== expectedConfirmation}
                    className="flex items-center gap-2 rounded-md bg-[#a64f4f] px-4 py-2 text-sm text-white hover:bg-[#b85a5a] disabled:cursor-not-allowed disabled:opacity-35"
                  >
                    <ResonanceActionIcon size="sm" tone="danger">{deleting ? <LoaderCircle size={11} className="animate-spin" /> : <ResonanceIcon kind="delete" size={12} />}</ResonanceActionIcon>
                    {deleting ? '备份并删除中' : '备份并删除'}
                  </button>
                </div>
              </div>
            </>}
        </Modal>

        <Modal
          open={updateInfo !== null}
          onClose={closeUpdateModal}
          closeDisabled={updating}
          className="max-w-md border-white/[0.08] bg-[#242424]"
          labelledBy="update-dialog-title"
        >
            {updateInfo && <>
              <div className="flex items-start justify-between border-b border-white/[0.06] p-5">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 rounded-md bg-[#6faaa0]/10 p-2 text-[#8fc8be]"><ResonanceIcon kind="refresh" size={19} /></div>
                  <div>
                    <h2 id="update-dialog-title" className="text-base font-medium text-tide">发现新版本</h2>
                    <p className="mt-1 text-xs text-wave">v{appVersion} → v{updateInfo.version}</p>
                  </div>
                </div>
                <ResonanceCloseButton onClick={closeUpdateModal} disabled={updating} />
              </div>

              <div className="p-5">
                {updateInfo.body && (
                  <div className="update-notes mb-4 max-h-60 overflow-y-auto rounded-md border border-white/[0.06] bg-white/[0.02] p-3 text-xs leading-5 text-wave">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{stripUpdateNotesFooter(updateInfo.body)}</ReactMarkdown>
                  </div>
                )}

                {updating && (
                  <div className="mb-4">
                    <div className="mb-1.5 flex items-center justify-between text-[11px] text-wave">
                      <span>{updateProgress < 100 ? '下载中' : '安装中'}...</span>
                      <span>{updateProgress}%</span>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-white/[0.06]">
                      <div className="h-full rounded-full bg-[#6faaa0] transition-all" style={{ width: `${updateProgress}%` }} />
                    </div>
                  </div>
                )}

                <div className="flex justify-end gap-2 pt-1">
                  <button onClick={closeUpdateModal} disabled={updating} className="px-4 py-2 text-sm text-wave hover:text-tide disabled:opacity-40">以后再说</button>
                  <button
                    onClick={handleInstallUpdate}
                    disabled={updating}
                    className="flex items-center gap-2 rounded-md bg-[#5a8a82] px-4 py-2 text-sm text-white hover:bg-[#6a9a92] disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <ResonanceActionIcon size="sm" tone="gold">{updating ? <LoaderCircle size={11} className="animate-spin" /> : <ResonanceIcon kind="download" size={12} />}</ResonanceActionIcon>
                    {updating ? '更新中' : '立即更新'}
                  </button>
                </div>
              </div>
            </>}
        </Modal>
      </div>
    </PageTransition>
  );
}
