import { useEffect, useState } from 'react';
import { type Update } from '@tauri-apps/plugin-updater';

/**
 * 更新公告预览 —— 开发环境下模拟多版本更新弹窗，
 * 用于在不发布新版本的情况下预览更新公告的 UI 效果。
 *
 * 触发方式（仅 dev 模式生效）：
 *   1. URL 参数：?dev-update-preview=1
 *   2. 快捷键：Ctrl + Shift + U
 */

// 多版本更新历史条目类型（与 SettingsPage 中的 UpdateHistoryEntry 保持一致）
export interface UpdateHistoryEntry {
  version: string;
  notes: string;
}

// 模拟数据：从 v0.6.2 升级到 v0.7.1，中间跨 5 个版本
const MOCK_UPDATE_HISTORY: UpdateHistoryEntry[] = [
  {
    version: '0.7.1',
    notes: `## 📦 v0.7.1

> 🗓️ **Release Date:** 2026-09-03
> 🔀 **Diff:** [\`v0.7.0...v0.7.1\`](https://github.com/juliy819/wuwa-gacha-tool/compare/v0.7.0...v0.7.1)

---

### 🐛 Bug Fixes

- 🐛 修复 OCR 识别时偶发的头像匹配偏移问题
- 🐛 修复设置页切换卡池时保底计数闪烁
- 🐛 修复导出文件名包含特殊字符时保存失败

### ⚡ Performance

- ⚡ 优化 Dashboard 首屏加载速度

---

> ⬇️ **下载文件见下方 Assets 区域**（Windows / Linux 安装包）

<sub>🤖 Auto-generated by GitHub Actions</sub>`,
  },
  {
    version: '0.7.0',
    notes: `## 📦 v0.7.0

> 🗓️ **Release Date:** 2026-09-01
> 🔀 **Diff:** [\`v0.6.3...v0.7.0\`](https://github.com/juliy819/wuwa-gacha-tool/compare/v0.6.3...v0.7.0)

---

### ✨ New Features

- ✨ 新增多版本更新公告展示，跨版本升级不再遗漏重要更新
- ✨ 新增五星历史分布图，直观查看出货节奏
- ✨ 新增模拟抽卡功能，支持自定义概率和保底
- ✨ 支持 OneDrive 云同步，多设备数据互通

### 🐛 Bug Fixes

- 🐛 修复大保底计数在跨卡池时的边界问题

### 🔧 Maintenance

- 🔧 升级 Tauri 到 v2
- 🔧 重构数据库查询层

---

> ⬇️ **下载文件见下方 Assets 区域**（Windows / Linux 安装包）

<sub>🤖 Auto-generated by GitHub Actions</sub>`,
  },
  {
    version: '0.6.3',
    notes: `## 📦 v0.6.3

> 🗓️ **Release Date:** 2026-08-20
> 🔀 **Diff:** [\`v0.6.2...v0.6.3\`](https://github.com/juliy819/wuwa-gacha-tool/compare/v0.6.2...v0.6.3)

---

### 🐛 Bug Fixes

- 🐛 修复导入历史记录时同秒多抽顺序错乱

---

> ⬇️ **下载文件见下方 Assets 区域**（Windows / Linux 安装包）

<sub>🤖 Auto-generated by GitHub Actions</sub>`,
  },
  {
    version: '0.6.2',
    notes: `## 📦 v0.6.2

> 🗓️ **Release Date:** 2026-08-10
> 🔀 **Diff:** [\`v0.6.1...v0.6.2\`](https://github.com/juliy819/wuwa-gacha-tool/compare/v0.6.1...v0.6.2)

---

### 🐛 Bug Fixes

- 🐛 修复暗金品质武器显示错误
- 🐛 修复设置页滚动条样式异常

---

> ⬇️ **下载文件见下方 Assets 区域**（Windows / Linux 安装包）

<sub>🤖 Auto-generated by GitHub Actions</sub>`,
  },
  {
    version: '0.6.1',
    notes: `## 📦 v0.6.1

> 🗓️ **Release Date:** 2026-07-28
> 🔀 **Diff:** [\`v0.6.0...v0.6.1\`](https://github.com/juliy819/wuwa-gacha-tool/compare/v0.6.0...v0.6.1)

---

### ⚡ Performance

- ⚡ OCR 识别速度提升 30%

### 📚 Documentation

- 📚 补充 Wiki 使用指南

---

> ⬇️ **下载文件见下方 Assets 区域**（Windows / Linux 安装包）

<sub>🤖 Auto-generated by GitHub Actions</sub>`,
  },
];

// 模拟用户当前版本号（用于计算哪些版本默认展开）
const MOCK_CURRENT_VERSION = '0.6.2';

// 构造假的 Update 对象
function buildMockUpdate(): Update {
  return {
    version: MOCK_UPDATE_HISTORY[0].version,
    body: MOCK_UPDATE_HISTORY[0].notes,
    date: new Date().toISOString(),
    rawJson: {
      version: MOCK_UPDATE_HISTORY[0].version,
      notes: MOCK_UPDATE_HISTORY[0].notes,
      pub_date: new Date().toISOString(),
      history: MOCK_UPDATE_HISTORY,
      platforms: {
        'windows-x86_64': {
          signature: 'mock-signature',
          url: 'https://example.com/mock-setup.exe',
        },
      },
    },
  } as unknown as Update;
}

export interface DevMockUpdatePreviewResult {
  /** mock 出的 Update 对象，可直接塞进更新弹窗 */
  mockUpdate: Update | null;
  /** 是否处于 mock 预览模式（用于显示提示条、禁用真实更新等） */
  isMockPreview: boolean;
  /** mock 使用的历史版本数据 */
  mockHistory: UpdateHistoryEntry[];
  /** mock 模式下模拟的当前版本号 */
  mockCurrentVersion: string;
}

/**
 * 开发环境更新公告预览 hook。
 *
 * 生产环境下直接返回空值，所有 mock 代码通过 tree-shaking 移除，
 * 不会出现在生产构建中。
 *
 * @example
 * ```tsx
 * const { mockUpdate, isMockPreview } = useDevMockUpdatePreview(location.search);
 * // 用 mockUpdate 替代真实 updateInfo 渲染弹窗
 * ```
 */
export function useDevMockUpdatePreview(search: string): DevMockUpdatePreviewResult {
  // 生产环境：直接返回空值，整段 mock 逻辑会被 Vite 移除
  if (!import.meta.env.DEV) {
    return {
      mockUpdate: null,
      isMockPreview: false,
      mockHistory: [],
      mockCurrentVersion: '',
    };
  }

  // —— 以下代码仅在开发环境执行 ——

  const [mockUpdate, setMockUpdate] = useState<Update | null>(null);

  // URL 参数触发
  useEffect(() => {
    const params = new URLSearchParams(search);
    if (params.get('dev-update-preview') === '1') {
      setMockUpdate(buildMockUpdate());
    }
  }, [search]);

  // 快捷键触发
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.ctrlKey && e.shiftKey && (e.key === 'U' || e.key === 'u')) {
        e.preventDefault();
        setMockUpdate((prev) => (prev ? null : buildMockUpdate()));
      }
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, []);

  return {
    mockUpdate,
    isMockPreview: mockUpdate !== null,
    mockHistory: MOCK_UPDATE_HISTORY,
    mockCurrentVersion: MOCK_CURRENT_VERSION,
  };
}
